[versions]
kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"
mccoroutines = "2.22.0"

paper-api = "26.2.build.+"
minecraft = "26.2"
vault-unlocked = "2.20"

paper-run = "3.1.0"
gversion = "1.11.0"
plugin-yaml-creator = "1.3.1"
buildconfig = "6.0.10"
configurate = "4.2.0"
lamp = "4.0.0-rc.18"
exposed = "1.3.0"
r2dbc-h2 = "1.1.0.RELEASE"
r2dbc-mariadb = "1.4.1"
r2dbc-mysql = "1.4.3"
ktlint = "14.2.0"
caffine = "3.2.4"
aedile = "3.0.4"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
vault-unlocked = { module = "net.milkbowl.vault:VaultUnlockedAPI", version.ref = "vault-unlocked" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
mccoroutine-folia-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-folia-api", version.ref = "mccoroutines" }
mccoroutine-folia-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-folia-core", version.ref = "mccoroutines" }
lamp-common  = { group = "io.github.revxrsal", name = "lamp.common", version.ref = "lamp" }
lamp-bukkit  = { group = "io.github.revxrsal", name = "lamp.bukkit", version.ref = "lamp" }
lamp-brigadier  = { group = "io.github.revxrsal", name = "lamp.brigadier", version.ref = "lamp" }
configurate-core  = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate-yaml  = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin  = { group = "org.spongepowered", name = "configurate-extra-kotlin", version.ref = "configurate" }
# Database
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-migration-r2dbc = { module = "org.jetbrains.exposed:exposed-migration-r2dbc", version.ref = "exposed" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2", version.ref = "r2dbc-h2" }
r2dbc-mariadb = { module = "org.mariadb:r2dbc-mariadb", version.ref = "r2dbc-mariadb" }
r2dbc-mysql = { module = "io.asyncer:r2dbc-mysql", version.ref = "r2dbc-mysql" }
caffine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffine" }
aedile = { module = "com.sksamuel.aedile:aedile-core", version.ref = "aedile" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gversion = { id = "com.peterabeles.gversion", version.ref = "gversion"}
plugin-yaml-creator-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "plugin-yaml-creator" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
paper-run = { id = "xyz.jpenilla.run-paper", version.ref = "paper-run" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[bundles]
mccoroutine = ["mccoroutine-folia-api", "mccoroutine-folia-core"]
configurate = ["configurate-core", "configurate-yaml", "configurate-extra-kotlin"]
lamp-bukkit = ["lamp-common", "lamp-bukkit", "lamp-brigadier"]
exposed = ["exposed-core", "exposed-r2dbc", "exposed-migration-r2dbc"]
r2dbc-drivers = ["r2dbc-h2", "r2dbc-mariadb", "r2dbc-mysql"]