[versions]
kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"
mccoroutines = "2.22.0"

paper-api = "26.2.build.+"
minecraft = "26.2"

paper-run = "3.0.2"
gversion = "1.11.0"
plugin-yaml-creator = "1.3.1"
buildconfig = "6.0.10"
configurate = "4.2.0"
lamp = "4.0.0-rc.18"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
mccoroutine-folia-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-folia-api", version.ref = "mccoroutines" }
mccoroutine-folia-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-folia-core", version.ref = "mccoroutines" }
lamp-common  = { group = "io.github.revxrsal", name = "lamp.common", version.ref = "lamp" }
lamp-bukkit  = { group = "io.github.revxrsal", name = "lamp.bukkit", version.ref = "lamp" }
lamp-brigadier  = { group = "io.github.revxrsal", name = "lamp.brigadier", version.ref = "lamp" }
configurate-core  = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate-yaml  = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin  = { group = "org.spongepowered", name = "configurate-extra-kotlin", version.ref = "configurate" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gversion = { id = "com.peterabeles.gversion", version.ref = "gversion"}
plugin-yaml-creator-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "plugin-yaml-creator" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
paper-run = { id = "xyz.jpenilla.run-paper", version.ref = "paper-run" }

[bundles]
mccoroutine = ["mccoroutine-folia-api", "mccoroutine-folia-core"]
configurate = ["configurate-core", "configurate-yaml", "configurate-extra-kotlin"]
lamp-bukkit = ["lamp-common", "lamp-bukkit", "lamp-brigadier"]